CREATE TABLE Usuario (
    ID INT UNSIGNED AUTO_INCREMENT,
    NOME VARCHAR(300) NOT NULL,
    EMAIL VARCHAR(300) NOT NULL,
    SENHA VARCHAR(32) NOT NULL,
    LOGRADOURO VARCHAR(50),
    BAIRRO VARCHAR(100),
    ESTADO CHAR(2),
    COMPLEMENTO VARCHAR(300),
    PRIMARY KEY (ID)
);

CREATE TABLE Telefone (
    USUARIO INT UNSIGNED,
    NUMERO VARCHAR(10) NOT NULL,
    PRIMARY KEY (USUARIO, NUMERO)
    CONSTRAINT FK_TEL_USU FOREIGN KEY (USUARIO) REFERENCES USUARIO(ID)
);

CREATE TABLE Hospital (
    ID INT UNSIGNED AUTO_INCREMENT,
    RESPONSAVEL VARCHAR(200) NOT NULL,
    CNPJ VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_HOSP_USU FOREIGN KEY (ID) REFERENCES USUARIO(ID)
);

CREATE TABLE Socorrista (
    ID INT UNSIGNED AUTO_INCREMENT,
    RG VARCHAR(16) NOT NULL,
    CPF VARCHAR(16) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_SOC_USU FOREIGN KEY ID REFERENCES USUARIO(ID)
);

CREATE TABLE Paciente (
    ID INT UNSIGNED AUTO_INCREMENT,
    TIPO_SANGUINEO VARCHAR(3) NOT NULL,
    CPF VARCHAR(16) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_SOC_USU FOREIGN KEY ID REFERENCES USUARIO(ID)
);

CREATE TABLE Doencas (
    ID INT UNSIGNED AUTO_INCREMENT,
    NOME VARCHAR(200) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE Medicamentos (
    ID INT UNSIGNED AUTO_INCREMENT,
    NOME VARCHAR(200) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE Alergias (
    ID INT UNSIGNED AUTO_INCREMENT,
    NOME VARCHAR(200) NOT NULL,
    PRIMARY KEY (ID)
);


CREATE TABLE Atende (
    ID INT UNSIGNED AUTO_INCREMENT,
    SOCORRISTA INT UNSIGNED,
    PACIENTE INT UNSIGNED,
    PRIMARY KEY (ID),
    CONSTRAINT FK_ATE_SOC FOREIGN KEY SOCORRISTA REFERENCES SOCORRISTA(ID),
    CONSTRAINT FK_ATE_PAC FOREIGN KEY PACIENTE REFERENCES PACIENTE(ID)
);

CREATE VIEW USULOGIN AS SELECT 